sudo: required
services:
    - docker
    
before_install:
    - docker build -t oonurkuru/react-tests -f ./client/Dockerfile.dev ./client
    
script:
    - docker run oonurkuru/react-tests npm run test
    
after_success:
    - docker build -t oonurkuru/multi-docker-container-client ./client
    - docker build -t oonurkuru/multi-docker-container-nginx ./nginx
    - docker build -t oonurkuru/multi-docker-container-server ./server
    - docker build -t oonurkuru/multi-docker-container-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push oonurkuru/multi-docker-container-client
    - docker push oonurkuru/multi-docker-container-nginx
    - docker push oonurkuru/multi-docker-container-server
    - docker push oonurkuru/multi-docker-container-worker
    
#deploy:
    #provider: elasticbeanstalk
    #region: us-east-1
    #app: multi-docker-container
    #env: MultiDockerContainer-env
    #bucket_name: elasticbeanstalk-us-east-1-033147592748
    #bucket_path: multi-docker-container
    #on:
        #branch: master
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key:
        #secure: $AWS_SECRET_KEY